name: Deploy FastAPI to Production

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd /home/mouzzam/fastapi-app/fastapi-demo
          git pull origin main
          source /home/mouzzam/fastapi-app/venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi